services:
  bank-db:
    image: postgres:18.1-alpine
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: banking
    volumes:
      - bank-db-data:/var/lib/postgresql 
      - ./sql/dump:/docker-entrypoint-initdb.d/

  bank-backend:
    image: bank
    depends_on: [bank-db]
    ports:
      - "127.0.0.1:8080:8080"
  
volumes:
  bank-db-data:

